version: '3.7'

services:
  sfpdf:
    image: aquitaine/sfrpg_pdf
    container_name: sfpdf
    ports:
      - "8081:8080"
    env_file:
      - config/commandbox.env
    volumes:
      - type: bind
        source: ./app
        target: /app